/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menues;

import Controlador.ControladorPersonaje;
import Modelo.Hostil;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author prouser
 */
public class CrearPj extends javax.swing.JFrame {

    private Hostil hostil;
    ControladorPersonaje controladorPersonaje = new ControladorPersonaje();
    Clip sonidoo = null;

    public CrearPj() {

        initComponents();

        this.getContentPane().setBackground(Color.BLACK);
        this.setSize(800, 600);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(CrearPj.EXIT_ON_CLOSE);

        lblDescripcion1.setVisible(false);
        lblDescripcion.setVisible(false);
        lblDescripcion2.setVisible(false);
        lblError.setVisible(false);

        try {
            sonidoo = AudioSystem.getClip();
        } catch (LineUnavailableException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            sonidoo.open(AudioSystem.getAudioInputStream(new File("src/Menues/Sonidos/main.wav")));
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        sonidoo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbClase = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        lblValor1 = new javax.swing.JLabel();
        lblValor2 = new javax.swing.JLabel();
        lblValor3 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        lblDescripcion2 = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblDescripcion1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDetective = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPolicia = new javax.swing.JLabel();
        lblExplorador = new javax.swing.JLabel();
        lblVolver = new javax.swing.JLabel();
        lblComenzar = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setTitle("The Best Game in the World");
        setBackground(new java.awt.Color(0, 0, 0));
        setName("The Best Game In the World"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        cmbClase.setBackground(new java.awt.Color(0, 0, 0));
        cmbClase.setFont(new java.awt.Font("TlwgMono", 1, 12)); // NOI18N
        cmbClase.setForeground(new java.awt.Color(255, 255, 255));
        cmbClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Detective", "Explorador", "Policia" }));
        cmbClase.setToolTipText("");
        cmbClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClaseActionPerformed(evt);
            }
        });
        getContentPane().add(cmbClase);
        cmbClase.setBounds(50, 150, 130, 22);

        txtNombre.setBackground(new java.awt.Color(0, 0, 0));
        txtNombre.setFont(new java.awt.Font("TlwgMono", 2, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setBorder(null);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(130, 52, 170, 20);

        lblValor1.setBackground(new java.awt.Color(255, 255, 255));
        lblValor1.setFont(new java.awt.Font("TlwgMono", 1, 14)); // NOI18N
        lblValor1.setForeground(new java.awt.Color(255, 255, 255));
        lblValor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblValor1);
        lblValor1.setBounds(270, 130, 30, 18);

        lblValor2.setBackground(new java.awt.Color(255, 255, 255));
        lblValor2.setFont(new java.awt.Font("TlwgMono", 1, 12)); // NOI18N
        lblValor2.setForeground(new java.awt.Color(255, 255, 255));
        lblValor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblValor2);
        lblValor2.setBounds(270, 180, 30, 18);

        lblValor3.setBackground(new java.awt.Color(255, 255, 255));
        lblValor3.setFont(new java.awt.Font("TlwgMono", 1, 12)); // NOI18N
        lblValor3.setForeground(new java.awt.Color(255, 255, 255));
        lblValor3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblValor3);
        lblValor3.setBounds(260, 155, 50, 18);

        lblError.setBackground(new java.awt.Color(0, 0, 0));
        lblError.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 204, 204));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblError.setOpaque(true);
        getContentPane().add(lblError);
        lblError.setBounds(320, 44, 170, 35);

        lblDescripcion2.setBackground(new java.awt.Color(0, 0, 0));
        lblDescripcion2.setFont(new java.awt.Font("TlwgMono", 1, 12)); // NOI18N
        lblDescripcion2.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDescripcion2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        lblDescripcion2.setOpaque(true);
        getContentPane().add(lblDescripcion2);
        lblDescripcion2.setBounds(310, 44, 20, 35);

        lblDescripcion.setBackground(new java.awt.Color(0, 0, 0));
        lblDescripcion.setFont(new java.awt.Font("TlwgMono", 1, 12)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDescripcion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        lblDescripcion.setOpaque(true);
        getContentPane().add(lblDescripcion);
        lblDescripcion.setBounds(320, 112, 170, 96);

        lblDescripcion1.setBackground(new java.awt.Color(0, 0, 0));
        lblDescripcion1.setFont(new java.awt.Font("TlwgMono", 1, 12)); // NOI18N
        lblDescripcion1.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDescripcion1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        lblDescripcion1.setOpaque(true);
        getContentPane().add(lblDescripcion1);
        lblDescripcion1.setBounds(310, 112, 20, 96);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/trampa.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 563, 290, 50);

        lblDetective.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/detective.png"))); // NOI18N
        getContentPane().add(lblDetective);
        lblDetective.setBounds(-30, 260, 160, 380);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/fuente.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 292, 240, 230);

        lblPolicia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/policia.png"))); // NOI18N
        getContentPane().add(lblPolicia);
        lblPolicia.setBounds(340, 270, 200, 210);

        lblExplorador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/explorador.png"))); // NOI18N
        getContentPane().add(lblExplorador);
        lblExplorador.setBounds(570, 240, 210, 340);

        lblVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/regresar.png"))); // NOI18N
        lblVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVolverMouseExited(evt);
            }
        });
        getContentPane().add(lblVolver);
        lblVolver.setBounds(550, 20, 210, 70);

        lblComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/comenzar.png"))); // NOI18N
        lblComenzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblComenzarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblComenzarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblComenzarMouseExited(evt);
            }
        });
        getContentPane().add(lblComenzar);
        lblComenzar.setBounds(70, 207, 210, 70);

        lblFondo.setBackground(new java.awt.Color(0, 0, 0));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/crearPj.jpg"))); // NOI18N
        lblFondo.setText("jLabel1");
        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    public JTextField getTxtNombre() {
//        return txtNombre;
//    }
//
//    public void setTxtNombre(JTextField txtNombre) {
//        this.txtNombre = txtNombre;
//    }

    private void cmbClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClaseActionPerformed
        if (cmbClase.getSelectedItem().equals("Detective")) {

            lblDescripcion.setText("<html>El Dective se caracteriza por su astucia y a habilidad en la pelea, es la "
                    + "clase más equilibrada del juego.</html>");
            lblValor1.setText("10");
            lblValor2.setText("10");
            lblValor3.setText("5/10");
            lblDescripcion.setVisible(true);
            lblDescripcion1.setVisible(true);
            lblDetective.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/detectivesobre.png")));

            lblExplorador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/explorador.png")));
            lblPolicia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/policia.png")));

        } else if (cmbClase.getSelectedItem().equals("Policia")) {

            lblDescripcion.setText("<html>Ser Policia no es fácil... La fuerza es importante para luchar contra las "
                    + "amenazas que encontrarás en esta historia.</html>");
            lblValor1.setText("12");
            lblValor2.setText("8");
            lblValor3.setText("4/12");
            lblDescripcion.setVisible(true);
            lblDescripcion1.setVisible(true);
            lblPolicia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/policiasobre.png")));

            lblExplorador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/explorador.png")));
            lblDetective.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/detective.png")));

        } else if (cmbClase.getSelectedItem().equals("Explorador")) {

            lblDescripcion.setText("<html>Para explorar hay que ser ágil y esa es una caracteristica de esta clase. "
                    + "Defensivo por naturaleza.</html>");
            lblValor1.setText("8");
            lblValor2.setText("12");
            lblValor3.setText("6/7");
            lblDescripcion.setVisible(true);
            lblDescripcion1.setVisible(true);
            lblExplorador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/exploradorsobre.png")));

            lblPolicia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/policia.png")));
            lblDetective.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/detective.png")));

        } else {

            lblDescripcion.setText("");
            lblValor1.setText("");
            lblValor2.setText("");
            lblValor3.setText("");
            lblDescripcion.setVisible(false);
            lblDescripcion1.setVisible(false);
            lblExplorador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/explorador.png")));
            lblPolicia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/policia.png")));
            lblDetective.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/detective.png")));
        }
    }//GEN-LAST:event_cmbClaseActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void lblVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseEntered
        lblVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/regresarsobre.png")));
    }//GEN-LAST:event_lblVolverMouseEntered

    private void lblVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseExited
        lblVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/regresar.png")));
    }//GEN-LAST:event_lblVolverMouseExited

    private void lblVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVolverMouseClicked
        Main main = null;
        try {
            main = new Main();
        } catch (LineUnavailableException | URISyntaxException | UnsupportedAudioFileException | IOException ex) {
            Logger.getLogger(CrearPj.class.getName()).log(Level.SEVERE, null, ex);
        }
        sonidoo.stop();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblVolverMouseClicked

    private void lblComenzarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComenzarMouseEntered
        lblComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/comenzarsobre.png")));
    }//GEN-LAST:event_lblComenzarMouseEntered

    private void lblComenzarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComenzarMouseExited
        lblComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menues/Imagenes/comenzar.png")));
    }//GEN-LAST:event_lblComenzarMouseExited

    private void lblComenzarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComenzarMouseClicked
        controladorPersonaje.agregarValores(txtNombre.getText(), cmbClase.getSelectedItem().toString());

        PantallaJuego pantallaJuego = new PantallaJuego(controladorPersonaje);

        if (txtNombre.getText().length() == 0 && cmbClase.getSelectedItem().equals("...")) {
            lblError.setVisible(true);
            lblError.setText("Falta colocar Nombre y Clase!");
            lblDescripcion2.setVisible(true);
        } else if (cmbClase.getSelectedItem().equals("...")) {
            lblError.setVisible(true);
            lblError.setText("Falta colocar Clase!");
            lblDescripcion2.setVisible(true);
        } else if (txtNombre.getText().length() == 0) {
            lblError.setVisible(true);
            lblError.setText("Falta colocar Nombre!");
            lblDescripcion2.setVisible(true);
        } else {
            sonidoo.stop();
            pantallaJuego.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_lblComenzarMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CrearPj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CrearPj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CrearPj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CrearPj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CrearPj().setVisible(true);
//
//            }
//
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbClase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblComenzar;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDescripcion1;
    private javax.swing.JLabel lblDescripcion2;
    private javax.swing.JLabel lblDetective;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblExplorador;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblPolicia;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JLabel lblValor2;
    private javax.swing.JLabel lblValor3;
    private javax.swing.JLabel lblVolver;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
